# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-Animation-Cards' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

  # Pods for Swift-Animation-Cards

end
